### ISSUE TITLE
EC2 Instances are not associated with the ECS Cluster

### ISSUE THREAD

**Issue by bdwellons** [infrablocks/terraform-aws-ecs-cluster#12]
This is likely user error here (me), but I've been trying to sort this out for 8 hours today and have failed to solve the problem. Below I've provided my base-network and ecs-cluster module configs. The problem I'm experiencing is that when I use a task definition and ecs service to deploy a container image in the cluster, it fails. The error is that there are no instances in my cluster.

![image](https://user-images.githubusercontent.com/1261298/80033032-0cb20c00-84ba-11ea-86f0-4f4407a090f6.png)

Can you see anything incorrect in my module config below? 
```
module "base_network" {
    source  = "infrablocks/base-networking/aws"
    version = "2.3.0"

    vpc_cidr                            = "10.0.0.0/16"
    region                              = "us-east-1"
    availability_zones                  = ["us-east-1a", "us-east-1b"]

    component                           = "dev-base-network"
    deployment_identifier               = "development"

    include_route53_zone_association    = "true"

    private_zone_id                     = module.route53.private_zone_id

    include_nat_gateway                 = "true"
}

module "ecs_cluster" {
    source                                  = "infrablocks/ecs-cluster/aws"
    version                                 = "2.2.0"

    region                                  = "us-east-1"
    vpc_id                                  = module.base_network.vpc_id
    subnet_ids                              = module.base_network.public_subnet_ids

    associate_public_ip_addresses           = "yes"

    component                               = "dev"
    deployment_identifier                   = "devx"

    cluster_name = "services"
    cluster_instance_ssh_public_key_path    = "~/.ssh/id_rsa.pub"
    cluster_instance_type                   = "t2.small"

    cluster_minimum_size                    = 2
    cluster_maximum_size                    = 10
    cluster_desired_capacity                = 2
}
```
Thanks in advance for any pointer you can give me here! I'm happy to contribute funds to your project in return.

**Comment by bdwellons** [comment]
I believe I see the issue @tobyclemson . When I look at the cluster name generated, it is in the form `<component>-<deployment_identifier>-<cluster-name>`. When I look at the cluster name each EC2 instance is associated with, it is in the form `<cluster_name>`. So my cluster is called `dev-devx-services`, but the EC2 instances are associated with cluster name `services`.

**Comment by tobyclemson** [comment]
Hi Brant,

Thanks for raising the issue, I'd like to understand a little better before merging your PR as I've used for a number of years and am currently using these two modules together without issue. There may be a regression but the tests are currently passing in [CI](https://app.circleci.com/pipelines/github/infrablocks/terraform-aws-ecs-cluster) and since the PR you've raised is backwards incompatible, it will cause any existing clusters to be recreated.

Currently, the ECS cluster name is generated from component, deployment identifier and cluster name to allow multiple clusters to be deployed in the same account. For example, I might have clusters: `services-blue-default`, `services-green-default` deployed from the same configuration. I might also want two clusters for the same component and deployment identifier, e.g., `services-blue-low-sensitivity` vs `services-blue-high-sensitivity`. I would like to retain this ability as I use it frequently right now.

The way the module works is to create the ECS cluster using the naming mechanism described and then it templates out the EC2 instance user data using the resulting ECS cluster name. See [line 35 in cluster.tf](https://github.com/infrablocks/terraform-aws-ecs-cluster/blob/31b01722f6f6df895edc44dfe2cee814bd767697/cluster.tf#L35) for how that value is accessed. This is interpolated into the [user-data script](https://github.com/infrablocks/terraform-aws-ecs-cluster/blob/31b01722f6f6df895edc44dfe2cee814bd767697/user-data/cluster.tpl#L2) to ensure the EC2 instance points at the cluster.

Are you overriding the user data somehow? The module actually allows this so you can customise the template and it will pass in the `cluster_name` template parameter so that you can produce your own user data script contents.

One other thing to note, the `base-networking` module expects `yes` or `no` for include_route53_zone_association and include_nat_gateway. These modules were originally written before terraform had boolean support and yes / no was chosen to avoid having a boolean in a string and to be more readable. If built now that 1st class boolean support is available I may make a different choice but again, I'm maintaining backwards compatibility.

Hope it helps, let me know what you find,
Toby

**Comment by bdwellons** [comment]
In Cluster.tf L#108, your setting the cluster name:
```
resource "aws_ecs_cluster" "cluster" {
  name = "${var.component}-${var.deployment_identifier}-${var.cluster_name}"
```

In security_groups.tf L10, you're setting the ClusterName tag:
```
ClusterName = var.cluster_name
```
So these are out of sync. Let me play with it some more and see what might be going on. I'm guessing my assumption that the ClusterName value in tags had some bearing on the actual cluster it belonged to was inaccurate.

**Comment by tobyclemson** [comment]
Tags are merely for searching within the AWS console or API and for classifying spending from a billing perspective. They don't have any functional purpose beyond that in terms of wiring. 

Where that `ClusterName` is set as a tag, there are also tags for `DeploymentIdentifier` and `Component` so rather than using the fully qualified cluster name, I'm just using the user provided cluster name. I can see that there is some ambiguity here since the same name has been used for the var as for the resource property. It might make sense to rename the var to something like `cluster_name_suffix` or `cluster_identifier` however not sure how to do that without backwards incompatibility.

**Comment by tobyclemson** [comment]
Also note that the test suite of this module presents a working configuration - take a look at the [prerequisites](https://github.com/infrablocks/terraform-aws-ecs-cluster/tree/master/spec/infra/prerequisites) and the [harness](https://github.com/infrablocks/terraform-aws-ecs-cluster/tree/master/spec/infra/harness) directories. Prerequisites defines the base network and harness defines the ECS cluster. This might give an indication of what's required for a working setup.

**Comment by bdwellons** [comment]
Some more testing currently, but looks like my problems were originating from the true/false vs yes/no values in the Base Network module. The documentation shows boolean. Changing those looks to be having the right affect now.

The one downstream issue I've had, and I'm only using Infrablocks modules, is that the load balancer created by the load balancer module kills my EC2 instances after 30s for failing health checks. Those instances were spun up the ECS Cluster module. That's next for me to overcome. Thanks again for timely responses. And the Infrablocks work has been both a great tool to learn on as well an expedient way to get a project off the ground quick.

**Comment by tobyclemson** [comment]
Ah! Sorry about the documentation, I'll look to update to prevent someone else having that issue. 

In terms of the load balancer modules, there are a few so not sure which one you're using. The ECS load balancer is a classic load balancer under the covers. Currently the health check isn't that configurable but you can configure the health check target. By default this is HTTP:80/health but if you were to change to TCP:80 it would retain instances in the ELB target group as long as they are listening for TCP connections on that port.

I'm glad InfraBlocks has been useful, I'm hoping to get around to documenting all of this better as I realise it's quite hard to get up and running with. Thanks for your persistence :).

**Comment by tobyclemson** [comment]
I pushed a [documentation update](https://github.com/infrablocks/terraform-aws-base-networking/commit/256bc232449e24df74d03ee694db23b9958684e8). Let me know if you feel anything more is needed.

**Comment by bdwellons** [comment]
For anyone who finds themselves in the same predicament, the issue was my fault. Your load balancer and the Cluster need to be in the same subnets. Either both in pubic or both in private.
