### ISSUE TITLE
Cloudwatch logs creation.

### ISSUE THREAD

**Issue by jarrettj** [infrablocks/terraform-aws-ecs-cluster#20]
H,

Good day.

Used your helpful module to get up and running quickly with ecs. However my tasks could not create a log group. Does the instance iam role not have to have log group permissions as well? See below:
![Screenshot 2020-11-06 at 09 58 55](https://user-images.githubusercontent.com/777547/98340929-c7e56100-2016-11eb-8883-cad98369963e.png)

Not sure if you have come across this before? Thanks.

Regards.
Jarrett

**Comment by tobyclemson** [comment]
Hey Jarrett,

I typically create the log group using terraform and therefore using whatever role terraform runs as. This log group will optionally (defualt: yes) create a log group for the cluster, for deposition host logs etc. and then I create one or more log groups per ECS service as part of an ECS service module. You can see an example of this in the [terraform-aws-ecs-service](https://github.com/infrablocks/terraform-aws-ecs-service) module.

If you do want to add log group creation to the instance profile of the cluster, you can override the policy by passing the `cluster_instance_iam_policy_contents` variable including the contents of the full policy you'd like to use and the module will use that instead of the default.

Let me know how it works out,
Thanks,
Toby

**Comment by jarrettj** [comment]
Ah! I see @tobyclemson . I can overwrite the policy. Great, will do that. 

I ended up naming the log group manually in the container_definitions json file. I also did not use the ecs service module you described. Will give your way a try. Thanks.

Regards.
JJ

**Comment by jarrettj** [comment]
I was using file() in my aws_ecs_task_definition resource container_definitions. Thought it would interpolate, but it does not.

Switched to templatefile() instead and passed module.ecs-cluster.log_group through to the container_definitions file.

All sorted now. :)

**Comment by tobyclemson** [comment]
Glad you got it resolved.
Thanks,
Toby
